### ISSUE TITLE
request: include Intuit TID on OAuthException and FMSException

### ISSUE THREAD

**Issue by pennello** [intuit/QuickBooks-V3-Java-SDK#128]
After discussing a recent support ticket with Intuit staff, we found that neither the `OAuthException` nor the `FMSException` include the Intuit TID.  These would be very helpful in the Intuit QBO API SDK in order for us to provide that context to the support staff when debugging issues with particular failed API calls.  I'd like to make a feature request to have that value included on these (and perhaps other?) exception classes to facilitate debugging.

Please let me know if I can provide any other information to make this feature request more precise or useful for you.

**Comment by shweta-intuitdev** [comment]
@pennello - Hi! Thanks for the feedback. The SDK version 6.0.6 now includes the intuit_tid and detailed information on the OAuthException class. We have not yet added it to the FMSException.

**Comment by pennello** [comment]
@shweta-intuitdev Hello!  You're welcome!  Thank you for your reply, and for the enhancement thus far.  We'll look forward to when the TID is available in addition on the FMS exception.  Thank you!

**Comment by praveenadg** [comment]
I will look into adding Intuit TID on FMSException

**Comment by pennello** [comment]
Thank you @praveenadg !

**Comment by yzheng988** [comment]
I'd like to work on the TID for OAuthException please confirm

**Comment by diana-derose** [comment]
@yzheng988  - OAuthException already had tid. You can take up on FMSException as this PR #149 only adds the getter/setter on the class but the code to set the value in FMSException is not handled.

**Comment by mani-sreekakula** [comment]
@diana-derose I have added the support to pass intuit_tid from classes extended FMSException and actually set the value in code while throwing.

**Comment by Emilyhbx01** [comment]
Hi, can you update IntuitBatchInterceptorProvider.java to throw FMSException with intuit_tid? Thanks.

**Comment by praveenadg** [comment]
Sure. Created this [PR](https://github.com/intuit/QuickBooks-V3-Java-SDK/pull/192)

**Comment by pennello** [comment]
Looks like this may be resolved as of https://github.com/intuit/QuickBooks-V3-Java-SDK/releases/tag/6.2.3!  We'll validate.  Thank you @praveenadg !

**Comment by sujitharamadass** [comment]
Closing the issue as the PR is already merged and released.
