### ISSUE TITLE
GZIPCompressor should not use default platform encoding

### ISSUE THREAD

**Issue by happyser** [intuit/QuickBooks-V3-Java-SDK#129]
GZIPCompressor.Compress method uses default platform encoding for string. While quickbooks service expects data in UTF-8

 public byte[] compress(String data, byte[] uploadFile) throws CompressionException {
...
                baos = new ByteArrayOutputStream();
                gzout = new GZIPOutputStream(baos);
                gzout.write(data.getBytes()); //WRONG! should be data.getBytes(StandardCharsets.UTF_8)

to test:
create Invoice using DataService.add

Invoice invoice = new Invoice()
...
MemoRef memo = new MemoRef();
memo.setValue("Guest: Júlia");
invoice.setCustomerMemo(memo);

**Comment by fjolin-intuit** [comment]
Closing. Fixed with PR #139
