### ISSUE TITLE
IAPlatformClient for different environments

### ISSUE THREAD

**Issue by LeonisX** [intuit/QuickBooks-V3-Java-SDK#13]
Hi 2 all SDK developers.

Now I use V3 Java API and faced with one difficulty.

I use `com.intuit.ia.connection.IAPlatformClient` class for receive accessToken. All work fine, but `IAPlatformClient` use hardcoded (private) `OAuthHelper`, it use hardcoded `IAHelperConfig`, it read properties from hardcoded file `ia.properties`.

Now I test application on `localhost`, and all work.

But after deploy, property `oauth_callback_url` from file `ia.properties` must be different, not http://localhost:8080/v1/qbo/auth/callback

Perhaps I did not quite understand the SDK and could not find a worthy solution to this problem. 

What can you recommend?

Thank you for your early reply.

**Comment by diana-derose** [comment]
Hi, You can create copy of ia.properties file in your project's resources folder and override the property values including callback url.
There's a sample here using an old version of the SDK that you might find useful
https://github.com/diana-derose/C2QB-Sample-Java/tree/master/src/main/resources

**Comment by LeonisX** [comment]
Diana, thanks for quick response. 

Let's explain.

Dev host: localhost:8080
Prod host: site-name.com

Callback urls for dev and prod must be different.

How this solved in our project (manual auth):

```
public void auth(HttpServletRequest request) {
        final OAuth10aService service = new ServiceBuilder()
                .apiKey(consumer_key)
                .apiSecret(consumer_secret)
                .callback(String.format("%s/callback", request.getRequestURL()))
                .build(QboApi.instance());
        OAuth1RequestToken requestToken = service.getRequestToken();
        ...
```

Now I migrate code to V3 Java SDK, and do not see the possibility of dynamically changing callback url.

What can you advise about this?

**Comment by diana-derose** [comment]
Hi, One way to handle this is to have your configs (ia.properties file) in a separate folder for each of your environments and configure your build script to use env as a parameter and copy the env specific property file to the resources folder during build time.
