### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of commons-codec:commons-codec:jar

### ISSUE THREAD

**Issue by Bing-ok** [intuit/QuickBooks-V3-Java-SDK#143]
Hi, there are multiple versions of <b><i>commons-codec:commons-codec</i></b> in <b><i>QuickBooks-V3-Java-SDK\ipp-v3-java-devkit</i></b>. As shown in the following dependency tree, according to Maven's “nearest wins” strategy, only <b><i>commons-codec:commons-codec:1.3</i></b> can be loaded, and <b><i>commons-codec:commons-codec:1.11</i></b> will be shadowed.

As <b><i>commons-codec:commons-codec:1.11</i></b> has not been loaded during the building process, several methods are missing. However, the missing methods:
<b><i>1. org.apache.commons.codec.binary.Base64: void init (int)</i></b>
<details>
<summary>Check for details of invocation</summary>
<pre><code>
paths------
&lt;com.intuit.ipp.interceptors.HTTPClientConnectionInterceptor: void execute(com.intuit.ipp.interceptors.IntuitMessage)&gt; QuickBooks-V3-Java-SDK\ipp-v3-java-devkit\target\classes
&lt;org.apache.http.impl.client.CloseableHttpClient: org.apache.http.client.methods.CloseableHttpResponse execute(org.apache.http.HttpHost,org.apache.http.HttpRequest)&gt; Repositories\org\apache\httpcomponents\httpclient\4.5.10\httpclient-4.5.10.jar
&lt;org.apache.http.impl.client.InternalHttpClient: org.apache.http.client.methods.CloseableHttpResponse doExecute(org.apache.http.HttpHost,org.apache.http.HttpRequest,org.apache.http.protocol.HttpContext)&gt; Repositories\org\apache\httpcomponents\httpclient\4.5.10\httpclient-4.5.10.jar
&lt;org.apache.http.impl.execchain.MainClientExec: org.apache.http.client.methods.CloseableHttpResponse execute(org.apache.http.conn.routing.HttpRoute,org.apache.http.client.methods.HttpRequestWrapper,org.apache.http.client.protocol.HttpClientContext,org.apache.http.client.methods.HttpExecutionAware)&gt; Repositories\org\apache\httpcomponents\httpclient\4.5.10\httpclient-4.5.10.jar
&lt;org.apache.http.impl.auth.HttpAuthenticator: void generateAuthResponse(org.apache.http.HttpRequest,org.apache.http.auth.AuthState,org.apache.http.protocol.HttpContext)&gt; Repositories\org\apache\httpcomponents\httpclient\4.5.10\httpclient-4.5.10.jar
&lt;org.apache.http.impl.auth.HttpAuthenticator: org.apache.http.Header doAuth(org.apache.http.auth.AuthScheme,org.apache.http.auth.Credentials,org.apache.http.HttpRequest,org.apache.http.protocol.HttpContext)&gt; Repositories\org\apache\httpcomponents\httpclient\4.5.10\httpclient-4.5.10.jar
&lt;org.apache.http.impl.auth.BasicScheme: org.apache.http.Header authenticate(org.apache.http.auth.Credentials,org.apache.http.HttpRequest,org.apache.http.protocol.HttpContext)&gt; Repositories\org\apache\httpcomponents\httpclient\4.5.10\httpclient-4.5.10.jar
&lt;org.apache.commons.codec.binary.Base64: void init (int)&gt;
</code></pre>
</details>

The above missing methods are actually referenced by <b><i>QuickBooks-V3-Java-SDK\ipp-v3-java-devkits</i></b>, which will cause “NoSuchMethodErrors” at runtime.

Suggested fixing solutions:
1. Upgrade dependency <b><i>commons-codec:commons-codec</i></b> from <b><i>1.3</i></b> to <b><i>1.11</i></b>.
2. Use configuration attribute &lt;dependencyManagement&gt; to unify the version of library <b><i>commons-codec:commons-codec</i></b> to be <b><i>1.11</i></b> in pacbot\commons\pac-batch-commons's pom file.
3. Use &lt;exclude&gt; to exclude <b><i>commons-codec:commons-codec:1.3</i></b> from the dependency tree
4. Change dependency <b><i>org.apache.httpcomponents:httpclient</i></b> from <b><i>4.5.10</i></b> to <b><i>4.0-alpha1</i></b>. Because one conflicting library version <b><i>commons-codec:commons-codec:1.3</i></b> is transitively introduced by <b><i>org.apache.httpcomponents:httpclient:4.5.10</i></b>. Changing dependency <b><i>org.apache.httpcomponents:httpclient</i></b> from <b><i>4.5.10</i></b> to <b><i>4.0-alpha1</i></b> can solve this dependency conflict.

Please let me know which solution do you prefer? I can submit a PR to fix it.

Thank you very much for your attention.
Best regards,

Dependency tree----
<details>
<summary>click for details</summary>
<pre><code>
[INFO] com.intuit.quickbooks-online:ipp-v3-java-devkit:jar:6.0.9
[INFO] +- com.intuit.quickbooks-online:ipp-v3-java-data:jar:6.0.8:compile
[INFO] |  +- org.jvnet.jaxb2_commons:jaxb2-basics-runtime:jar:1.11.1:compile
[INFO] |  +- joda-time:joda-time:jar:2.1:compile
[INFO] |  +- org.jvnet.jaxb2_commons:jaxb2-commons-lang:jar:2.4:compile
[INFO] |  |  \- org.apache.commons:commons-lang3:jar:3.2.1:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.10:compile
[INFO] |  +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO] |  |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] |  +- org.glassfish.jaxb:jaxb-runtime:jar:2.3.1:compile
[INFO] |  |  +- (javax.xml.bind:jaxb-api:jar:2.3.1:compile - omitted for duplicate)
[INFO] |  |  +- org.glassfish.jaxb:txw2:jar:2.3.1:compile
[INFO] |  |  +- com.sun.istack:istack-commons-runtime:jar:3.0.7:compile
[INFO] |  |  +- org.jvnet.staxex:stax-ex:jar:1.8:compile
[INFO] |  |  +- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.15:compile
[INFO] |  |  \- (javax.activation:javax.activation-api:jar:1.2.0:compile - omitted for duplicate)
[INFO] |  +- (com.sun.xml.bind:jaxb-core:jar:2.3.0:compile - omitted for duplicate)
[INFO] |  +- (com.sun.xml.bind:jaxb-impl:jar:2.3.0:compile - omitted for duplicate)
[INFO] |  +- (org.slf4j:slf4j-api:jar:1.7.28:compile - omitted for duplicate)
[INFO] |  +- (org.apache.httpcomponents:httpclient:jar:4.5.10:compile - omitted for duplicate)
[INFO] |  +- (org.apache.httpcomponents:httpcore:jar:4.4.12:compile - omitted for duplicate)
[INFO] |  \- (org.apache.ant:ant:jar:1.10.6:compile - omitted for duplicate)
[INFO] +- cglib:cglib:jar:3.2.12:compile
[INFO] |  \- org.ow2.asm:asm:jar:7.1:compile
[INFO] +- asm:asm-commons:jar:3.3.1:compile
[INFO] |  \- asm:asm-tree:jar:3.3.1:compile
[INFO] |     \- asm:asm:jar:3.3.1:compile
[INFO] +- com.sun.mail:javax.mail:jar:1.6.1:compile
[INFO] |  \- javax.activation:activation:jar:1.1:compile
[INFO] +- com.google.code.gson:gson:jar:2.8.1:compile
[INFO] +- javax.servlet:servlet-api:jar:2.4:provided
[INFO] +- com.sun.xml.bind:jaxb-impl:jar:2.3.0:compile
[INFO] +- com.sun.xml.bind:jaxb-core:jar:2.3.0:compile
[INFO] +- oauth.signpost:signpost-core:jar:1.2.1.1:compile
[INFO] |  \- <b>commons-codec:commons-codec:jar:1.3:compile</b>
[INFO] +- oauth.signpost:signpost-commonshttp4:jar:1.2:compile
[INFO] |  +- (oauth.signpost:signpost-core:jar:1.2:compile - omitted for conflict with 1.2.1.1)
[INFO] |  +- (org.apache.httpcomponents:httpcore:jar:4.0.1:compile - omitted for conflict with 4.4.12)
[INFO] |  \- (org.apache.httpcomponents:httpclient:jar:4.0.1:compile - omitted for conflict with 4.5.10)
[INFO] +- commons-configuration:commons-configuration:jar:1.6:compile
[INFO] |  +- commons-lang:commons-lang:jar:2.4:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  +- commons-digester:commons-digester:jar:1.8:compile
[INFO] |  |  +- commons-beanutils:commons-beanutils:jar:1.7.0:compile
[INFO] |  |  |  \- (commons-logging:commons-logging:jar:1.0.3:compile - omitted for conflict with 1.1.1)
[INFO] |  |  \- (commons-logging:commons-logging:jar:1.1:compile - omitted for conflict with 1.1.1)
[INFO] |  \- commons-beanutils:commons-beanutils-core:jar:1.8.0:compile
[INFO] |     \- (commons-logging:commons-logging:jar:1.1.1:compile - omitted for duplicate)
[INFO] +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] +- commons-io:commons-io:jar:2.5:compile
[INFO] +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.9.10:compile
[INFO] |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.9.10:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.9.10:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.9.10:compile
[INFO] |  |     +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.9.10:compile - omitted for duplicate)
[INFO] |  |     \- (com.fasterxml.jackson.core:jackson-core:jar:2.9.10:compile - omitted for duplicate)
[INFO] |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.9.10:compile
[INFO] |     +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.9.10:compile - omitted for duplicate)
[INFO] |     +- (com.fasterxml.jackson.core:jackson-core:jar:2.9.10:compile - omitted for duplicate)
[INFO] |     \- (com.fasterxml.jackson.core:jackson-databind:jar:2.9.10:compile - omitted for duplicate)
[INFO] +- org.jmockit:jmockit:jar:1.25:test
[INFO] +- org.slf4j:slf4j-api:jar:1.7.28:compile
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.5.10:compile
[INFO] |  +- (org.apache.httpcomponents:httpcore:jar:4.4.12:compile - omitted for duplicate)
[INFO] |  +- (commons-logging:commons-logging:jar:1.2:compile - omitted for conflict with 1.1.1)
[INFO] |  \- <b>(commons-codec:commons-codec:jar:1.11:compile - omitted for conflict with 1.3)</b>
[INFO] +- org.apache.httpcomponents:httpcore:jar:4.4.12:compile
[INFO] +- org.testng:testng:jar:6.14.3:test
[INFO] |  +- com.beust:jcommander:jar:1.72:test
[INFO] |  \- org.apache-extras.beanshell:bsh:jar:2.0b6:test
[INFO] +- org.slf4j:slf4j-log4j12:jar:1.7.28:test
[INFO] |  +- (org.slf4j:slf4j-api:jar:1.7.28:test - omitted for duplicate)
[INFO] |  \- (log4j:log4j:jar:1.2.17:test - omitted for duplicate)
[INFO] +- log4j:log4j:jar:1.2.17:test
[INFO] \- org.apache.ant:ant:jar:1.10.6:compile
[INFO]    +- org.apache.ant:ant-launcher:jar:1.10.6:compile
[INFO]    |  \- (com.sun:tools:jar:1.8.0:system - omitted for duplicate)
[INFO]    \- com.sun:tools:jar:1.8.0:system
</code></pre>
</details>

**Comment by Bing-ok** [comment]
Could you help me review this issue? 👍 Thanks! @nimisha84

**Comment by fjolin-intuit** [comment]
Hi @Bing-ok - Thanks for documenting this so thoroughly.  We have hacktoberfest going on now and would love for you to contribute. Your first suggested solution looks good - but I'll leave it up to you :)

**Comment by Bing-ok** [comment]
Thanks for your support. I have submitted the PR. @fjolin-intuit
