### ISSUE TITLE
Unable to get ReimburseCharge query result

### ISSUE THREAD

**Issue by b69liu** [intuit/QuickBooks-V3-Java-SDK#155]
When I execute the query and fetch the result, it should give me a list with size of 5
`String sql =  "Select * from ReimburseCharge Where HasBeenInvoiced = false";`
`QueryResult queryResult = this.service.executeQuery(sql);`
But I got an empty list, as
`queryResult.getEntities().size()` is 0
`queryResult.getTotalCount()` is 5

My environment:
ipp-v3-java-data: 6.1.0
ipp-v3-java-devkit: 6.1.0
oauth2-platform-api: 6.1.0
Java SE 14.0.2
Windows 10

I have also tried to fetch the ReimburseCharge in PHP SDK, and Postman, and they all worked.

**Comment by b69liu** [comment]
After debugging for few days, I find the problem is that the ReimburseCharge class is not registered in the type locator.
I made a local clone and added 
`put("ReimburseCharge", ReimburseCharge.class);` 
in JsonResourceTypeLocator.java below
`put("RefundReceipt", RefundReceipt.class);`
Then it is working!

**Comment by fjolin-intuit** [comment]
Hi @b69liu. thanks for looking into this.  I'll be adding your fix and testing today and will do a release.  Much appreciated!

**Comment by fjolin-intuit** [comment]
Fixed in latest release - thanks @b69liu
