### ISSUE TITLE
Migrating from QuickBooks Desktop to QuickBooks Online 

### ISSUE THREAD

**Issue by MarErm27** [intuit/QuickBooks-V3-Java-SDK#171]
Hello!
I was wondering if someone may be able to point me in the right direction.
There is a program that fetches bills, invoices and switches from site in JSON format, it converts it to XML and sends it to QuickBooks Desktop using QuickBooks Web Connector. How to make it to send these XML to QuickBooks Online instead of QuickBooks Desktop?

**Comment by fjolin-intuit** [comment]
Hi @MarErm27! I am not sure what program you are working with exactly, and so I cannot speak to its intended functionality with QBO or QBD.  That being said, the Java sdk (or any of our supported SDKs for that matter) work under the premise that a connection is established with a Quickbooks Online company.  My suggestion would be to contact the app makers support, or look for an app that suits your needs at apps.com.
