### ISSUE TITLE
Error 6000 on executeBatchAsync()

### ISSUE THREAD

**Issue by prowave** [intuit/QuickBooks-V3-Java-SDK#180]
I am trying to add 30 Accounts with `DataService.executeBatchAsync()`, and when I inspect my response in the callbackHandler ,all of the requests to add an `Account` entity are faulted with:

```
6000

Business Validation Error: You cannot enter more than 50 characters in the request_id field. You tried entering 8182e07bba..., which is 68 characters.
```

The request_id starting with `8182e07bba...` seems to be the same for every item in the batch.

I am not setting `request_id` to my knowledge.

My `bId` for the operations in the list are confirmed UUIDs that are only 36 characters in length.

Thanks for the assistance on this one.  Probably something stupid I missed. :)

Env:
amazon-corretto-15
sdk 6.2..1

Thanks,
Dave

**Comment by prowave** [comment]
Update: I turned on DEBUG logging and see this in the logs.

https://sandbox-quickbooks.api.intuit.com/v3/company/4625319964620932638/batch?requestid=86e1e8438fd9413587c2bd17f4185b13&minorversion=63& 

The requestid is clearly 32 characters.

**Comment by sujitharamadass** [comment]
@prowave Do you still need help on this?
