### ISSUE TITLE
Get deleted records

### ISSUE THREAD

**Issue by OArtyomov** [intuit/QuickBooks-V3-Java-SDK#19]
No possibility to get ids of deleted records using this API, or I missed something

**Comment by diana-derose** [comment]
Hi, For name list entities such as customer, vendor etc you can get the deleted records by querying using active flag as false. 
Sample query to get deleted vendors - select * from vendor where active = false

For transaction entities such as invoice, bill etc the delete operation hard deletes the record, so there is no way to get the id back, unless you call CDC endpoint (Dataservice.executeCDCQuery) or have subscribed for webhooks.
https://developer.intuit.com/docs/0100_quickbooks_online/0300_references/0000_programming_guide/0020_webhooks
