### ISSUE TITLE
Exclude the wrong library

### ISSUE THREAD

**Issue by kamiltrantvananh** [intuit/QuickBooks-V3-Java-SDK#201]
https://github.com/intuit/QuickBooks-V3-Java-SDK/blob/a306e6c9aeb844269dfcad05cd49f0ec68aa062e/ipp-v3-java-devkit/pom.xml#L91

Library `commons-configuration:1.6` use `commons-beanutils-core` which is vulnerable.

**Comment by sujitharamadass** [comment]
@kamiltrantvananh We will include the PR in the next release. Thank you.
