### ISSUE TITLE
search Item with apostrophe name

### ISSUE THREAD

**Issue by TheMalloum** [intuit/QuickBooks-V3-Java-SDK#202]
Hi ,

I have the item name below : 

`String name ="My name's"`

i want to search a item with this name like below : 
   `protected Item itemProxy = GenerateQuery.createQueryEntity(Item.class);
   String sql = select($(itemProxy)).where($(itemProxy.getName()).eq(name)).generate();
   QueryResult queryResult = service.executeQuery(sql);`

cause the apostrophe the request does not works.

Thank you

**Comment by TheMalloum** [comment]
the item name  in the QuickBooks is My name\'s 

i made my search with **My name\\'s**  and  **My name\'s**  and the both do not work.

**Comment by sujitharamadass** [comment]
@TheMalloum Can you please try with My name\\'s
