### ISSUE TITLE
Timezone for metadata fields `createDateTime` and `updateDateTime` is unavailable

### ISSUE THREAD

**Issue by ede-n** [intuit/QuickBooks-V3-Java-SDK#26]
The REST api returns a date time string with TimeZone, but the java SDK returns just the `Date` from which one cannot get the Timezone.

```
public class ModificationMetaData
    implements Serializable, Equals, HashCode
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "CreatedByRef")
    protected ReferenceType createdByRef;
    @XmlElement(name = "CreateTime", type = String.class)
    @XmlJavaTypeAdapter(DateTimeAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected Date createTime;
    @XmlElement(name = "LastModifiedByRef")
    protected ReferenceType lastModifiedByRef;
    @XmlElement(name = "LastUpdatedTime", type = String.class)
    @XmlJavaTypeAdapter(DateTimeAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected Date lastUpdatedTime;
```

**Comment by diana-derose** [comment]
Hi, The API returns date in PST, so does the SDK, however the SDK returns it in the following format "Tue May 17 10:36:03 PDT 2016" while the API returns it as 2016-05-17T10:36:03-07:00. Let me know if you are seeing anything different.

**Comment by ede-n** [comment]
Thank you. Does that mean QuickBooks returns `createTime` always in `PST/PDT`?

**Comment by diana-derose** [comment]
Yes, but let me also create a bug on our end to make sure SDK returns the same format as API.

**Comment by ede-n** [comment]
Thank you.
