### ISSUE TITLE
finalize method intercepted by MyMethodInterceptor

### ISSUE THREAD

**Issue by psundar-bill** [intuit/QuickBooks-V3-Java-SDK#27]
The MyMethodInterceptor intercepts the finalize method. This causes the ThreadLocal<Path> in GenerateQuery class to have a huge "alize.alize.alize... " consuming a lot of heap space.

The usage example is to create a proxy object using GenerateQuery.createQueryEntity(Customer.class)

**Comment by diana-derose** [comment]
Hi, I'll add it to our backlog to look into this. We have had some issues with the methods in GenerateQuery class and I wouldn't recommend using it.
Use the executeQuery method in the DataService class instead. Here's a sample below-
https://github.com/IntuitDeveloper/SampleApp-CRUD-Java/blob/master/src/main/java/com/intuit/developer/sampleapp/crud/entities/customer/CustomerQuery.java
