### ISSUE TITLE
OAuth2PlatformClient.revokeToken doesn't return new revokeToken but only `success`

### ISSUE THREAD

**Issue by binlufluxx** [intuit/QuickBooks-V3-Java-SDK#35]
When revokenToken successes, it doesn't return the raw response which contains new refreshToken.
https://github.com/intuit/QuickBooks-V3-Java-SDK/blob/aa37ab513f5d6f4eb94cfa1f53dadf0086531d84/oauth2-platform-api/src/main/java/com/intuit/oauth2/client/OAuth2PlatformClient.java#L199

**Comment by diana-derose** [comment]
Hi - RevokeToken invalidates the tokens, it doesn't return anything. If you need to refresh token, you should use revokeToken method.
