### ISSUE TITLE
Payments data and service classes?

### ISSUE THREAD

**Issue by wendelicious** [intuit/QuickBooks-V3-Java-SDK#39]
I see that there is the [`payments-reference-implementation`](https://github.com/IntuitDeveloper/SampleApp-ECommerce_Payments_SalesReceipt-Java/tree/master/libs/payments-reference-implementation) project embedded in its project, but I can't seem to find where the Payments SDK/lib _should_ be coming from.

The [tutorial online](https://developer.intuit.com/v2/ui#/emulator?workflow=ecommerce) shows using the `Charge` class, which seems to come from the `com.intuit.sample.payment.model` package, which isn't readily avialable in the [`ipp-v3-java-data` project](https://github.com/intuit/QuickBooks-V3-Java-SDK/tree/develop/ipp-v3-java-data/src/main/java/com/intuit/ipp/data).  [Maven Central](https://search.maven.org/#search%7Cga%7C1%7Ccom.intuit.quickbooks-online) doesn't seem to have any other artifacts for me to depend on.

So, what is the right way to do this?  Are the examples wrong?  Is the SDK intended to be embedded like this?  There is no path to green for me, shy of [re-implementing the REST interface](https://github.com/IntuitDeveloper/SampleApp-Payments-Java/blob/master/src/main/java/com/intuit/sample/payment/helper/PaymentHelper.java), which is a terrible answer.

Cross-posting, as I don't know where the "best" place to reach QBO developer support.

**Comment by wendelicious** [comment]
Also, [as per your instructions](https://developer.intuit.com/docs/00_quickbooks_online/2_build/40_sdks/02_java/0002_install_the_java_sdk), should I really be using version 2.9.0 from March 2017?  Is there any reason I should _not_ be using 4.0.5 from last week?

**Comment by wendelicious** [comment]
I just [saw this](https://developer.intuit.com/docs/00_quickbooks_payments/2_build/using_an_sdk_to_integrate_with_the_payments_api) which makes no sense to me. 

What is the suggested path forward to charge a tokenized card within my Java application?

**Comment by diana-derose** [comment]
Answered to your questions in the other GitHub repo. This SDK currently doesn't support Payment APIs.
