### ISSUE TITLE
Qbo France Support

### ISSUE THREAD

**Issue by davidseywald** [intuit/QuickBooks-V3-Java-SDK#40]
Hello,
Can I use/configure this SDK for Qbo France. Since they have different endpoints,
it would be good if you could configure the country and it will automatically switch the endpoint urls.
For example in the documentation of the TrialBalance Report it states:

"SAMPLE QUERY
For non-FR locales:
BaseURL/v3/company/1386066315/reports/TrialBalance
For FR locale:
BaseURL/v3/company/1386066315/reports/TrialBalanceFR?minorversion=4"

Any ideas/news would be highly appreciated!

**Comment by diana-derose** [comment]
Thanks for the feedback, I'll add this feature in the next release in a couple of weeks.

**Comment by diana-derose** [comment]
@davidseywald - Until the fix, you can pass the report name as a String as a workaround.
For France-
Report report = service.executeReport("TrialBalanceFR");
For others,
Report report = service.executeReport(ReportName.TRIALBALANCE.toString());

**Comment by davidseywald** [comment]
@diana-derose - Thank you for the quick reply.
This workaround works.

**Comment by davidseywald** [comment]
Another Question/Issue regarding QBO France. I am looking for the SIRET/SIREN Number of the company. Is this somewhere exposed in the sdk? Thanks.

**Comment by davidseywald** [comment]
@diana-derose - Thank you. The RCS/Siren number will work for now. Though it would be nice in the future to also be able to get the Siret number(s).

**Comment by diana-derose** [comment]
Thanks @davidseywald - I have created an enhancement request for the team to add this field in the API. Here's the internal jira no. (ACCTG-16436) for your reference. Closing this issue since the SDK will support once it's available in the API.
