### ISSUE TITLE
Fails to build with Maven version 3.5.2

### ISSUE THREAD

**Issue by tbigueres** [intuit/QuickBooks-V3-Java-SDK#41]
Hi, 

I'm currently running into an issue with quickbooks. 
It seems that I cannot get my project to build when I include the three following dependencies in my pom.xml  :  

`                <dependency>
			<groupId>com.intuit.quickbooks-online</groupId>
			<artifactId>oauth2-platform-api</artifactId>
			<version>4.0.5</version>
		</dependency>
		<dependency>
			<groupId>com.intuit.quickbooks-online</groupId>
			<artifactId>ipp-v3-java-data</artifactId>
			<version>4.0.5</version>
		</dependency>
		<dependency>
			<groupId>com.intuit.quickbooks-online</groupId>
			<artifactId>ipp-v3-java-devkit</artifactId>
			<version>4.0.5</version>
		</dependency>`

When building with maven 3.3.9 it works all good, but when trying to use version 3.5.2 I have the following error : 

`[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for net.parislabs:nove:war:1.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-resources-plugin is missing. @ line 444, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Client::nove 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> jetty-maven-plugin:9.3.7.v20160115:run (default-cli) > test-compile @ nove >>>
[INFO]
[INFO] --- git-commit-id-plugin:2.2.3:revision (get-the-git-infos) @ nove ---
[INFO]
[INFO] --- maven-thrift-plugin:0.1.11:compile (thrift-sources) @ nove ---
[INFO]
[INFO] --- aspectj-maven-plugin:1.8:compile (default) @ nove ---
[INFO] Showing AJC message detail for messages of types: [error, warning, fail]
[INFO]
[INFO] --- aspectj-maven-plugin:1.8:test-compile (default) @ nove ---
[INFO] Showing AJC message detail for messages of types: [error, warning, fail]
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ nove ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 20 resources
[INFO] Copying 35 resources
[INFO] Copying 89 resources
[INFO] skip non existing resourceDirectory /Users/thoma/Documents/workspace/nove/resources/dev
[INFO] Copying 1 resource
[INFO]
[INFO] --- pages-mapping-plugin:3.15.4-SNAPSHOT:generate-pages (default) @ nove ---
[INFO] Generating Pages.java from existing Resources
[INFO] 		Found a Resource endpoint: SandboxResource_get
[INFO] 		Found a Resource endpoint: UserValidationResource_get
[INFO] 		Found a Resource endpoint: LoginResource_get
[INFO] 		Found a Resource endpoint: LoginResource_directLogin
[INFO] 		Found a Resource endpoint: LoginResource_directLoginWithEncodedPassword
[INFO] 		Found a Resource endpoint: LoginResource_logAs
[INFO] 		Found a Resource endpoint: LoginResource_unlogAs
[INFO] 		Found a Resource endpoint: LoginResource_directLoginWithCryptedToken
[INFO] 		Found a Resource endpoint: OpenIdResource_redirectAction
[INFO] 		Found a Resource endpoint: OpenIdResource_validateAndRedirect
[INFO] 		Found a Resource endpoint: OpenIdResource_validateAndClose
[INFO] 		Found a Resource endpoint: AdminResource_get
[INFO] 		Found a Resource endpoint: AdminResource_getAction
[INFO] 		Found a Resource endpoint: I18nResource_getInterface
[INFO] 		Found a Resource endpoint: I18nResource_getDashboard
[INFO] 		Found a Resource endpoint: HomeResource_get
[INFO] 		Found a Resource endpoint: HomeResource_error
[INFO] 		Found a Resource endpoint: OperationResource_listOperation
[INFO] 		Found a Resource endpoint: OperationResource_editContrat
[INFO] 		Found a Resource endpoint: OperationResource_validateContract
[INFO] 		Found a Resource endpoint: OperationResource_operationReport
[INFO] 		Found a Resource endpoint: OperationResource_analystOperationReport
[INFO] 		Found a Resource endpoint: OperationResource_analystAnalysisReport
[INFO] 		Found a Resource endpoint: OperationResource_emitterAnalysisReport
[INFO] 		Found a Resource endpoint: OperationResource_dispatchOperation
[INFO] 		Found a Resource endpoint: ContractGeneratorResource_generatePDF
[INFO] 		Found a Resource endpoint: ContractResource_pdfBeforeReview
[INFO] 		Found a Resource endpoint: ContractResource_sendToYousign
[INFO] 		Found a Resource endpoint: ContractResource_listContract
[INFO] 		Found a Resource endpoint: ContractResource_viewNDAContract
[INFO] 		Found a Resource endpoint: ContractResource_emitterViewContract
[INFO] 		Found a Resource endpoint: AdminResource_enumEdit
[INFO] 		Found a Resource endpoint: UserResource_account
[INFO] 		Found a Resource endpoint: UserResource_generatePassword
[INFO] 		Found a Resource endpoint: CompanyResource_manageUsers
[INFO] 		Found a Resource endpoint: DashboardResource_get
[INFO] 		Found a Resource endpoint: QuickbooksResource_callbackFromLogin
[INFO] 		Found a Resource endpoint: QuickbooksResource_refreshAccessToken
[INFO] 		Found a Resource endpoint: QuickbooksResource_allowAuth
[INFO] 		Found a Resource endpoint: NotificationResource_list
[INFO] 		Found a Resource endpoint: PerfResource_summary
[INFO] 		Found a Resource endpoint: PerfResource_info
[INFO] 		Found a Resource endpoint: BounceResource_get
[INFO] 		Found a Resource endpoint: EmailValidationResource_validateEmail
[INFO] 		Found a Resource endpoint: EmailValidationResource_validateRecoveryEmail
[INFO] No changes needed
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ nove ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ nove ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/thoma/Documents/workspace/nove/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ nove ---
[INFO] Compiling 1 source file to /Users/thoma/Documents/workspace/nove/target/test-classes
[INFO]
[INFO] <<< jetty-maven-plugin:9.3.7.v20160115:run (default-cli) < test-compile @ nove <<<
[INFO]
[INFO]
[INFO] --- jetty-maven-plugin:9.3.7.v20160115:run (default-cli) @ nove ---
[INFO] Logging initialized @22154ms
[WARNING]  !exist file:///Users/thoma/Documents/workspace/nove/target/nove-1.0.0-SNAPSHOT
[INFO] Configuring Jetty for project: Client::nove
[INFO] webAppSourceDirectory not set. Trying src/main/webapp
[INFO] webAppSourceDirectory /Users/thoma/Documents/workspace/nove/src/main/webapp does not exist. Trying /Users/thoma/Documents/workspace/nove/target/webapp-tmp
[INFO] Reload Mechanic: automatic
[INFO] Classes = /Users/thoma/Documents/workspace/nove/target/classes
[INFO] Applying context xml file /Users/thoma/Documents/workspace/nove/target/classes/jetty-context.xml
[INFO] Context path = /
[INFO] Tmp directory = /Users/thoma/Documents/workspace/nove/target/tmp
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides = /Users/thoma/Documents/workspace/nove/target/classes/web.xml
[INFO] web.xml file = null
[INFO] Webapp directory = /Users/thoma/Documents/workspace/nove/target/webapp-tmp
[INFO] jetty-9.3.7.v20160115
[INFO] [main]: [10:59:59] [WebappConfig] : This application is running in stage DEVELOPMENT
Aug 29, 2018 11:00:02 AM org.mongodb.morphia.logging.MorphiaLoggerFactory chooseLoggerFactory
INFOS: LoggerImplFactory set to org.mongodb.morphia.logging.jdk.JDKLoggerFactory
[INFO] Started ServerConnector@5ddaf631{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
[INFO] Jetty server exiting.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.889 s
[INFO] Finished at: 2018-08-29T11:00:02+02:00
[INFO] Final Memory: 108M/1067M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.jetty:jetty-maven-plugin:9.3.7.v20160115:run (default-cli) on project nove: Execution default-cli of goal org.eclipse.jetty:jetty-maven-plugin:9.3.7.v20160115:run failed: An API incompatibility was encountered while executing org.eclipse.jetty:jetty-maven-plugin:9.3.7.v20160115:run: java.lang.VerifyError: class net.sf.cglib.core.DebuggingClassWriter overrides final method visit.(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.eclipse.jetty:jetty-maven-plugin:9.3.7.v20160115
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/jetty-maven-plugin/9.3.7.v20160115/jetty-maven-plugin-9.3.7.v20160115.jar
[ERROR] urls[1] = file:/Users/thoma/.m2/repository/org/sonatype/sisu/sisu-inject-bean/2.1.1/sisu-inject-bean-2.1.1.jar
[ERROR] urls[2] = file:/Users/thoma/.m2/repository/org/sonatype/sisu/sisu-guice/2.9.4/sisu-guice-2.9.4-no_aop.jar
[ERROR] urls[3] = file:/Users/thoma/.m2/repository/org/codehaus/plexus/plexus-utils/2.0.6/plexus-utils-2.0.6.jar
[ERROR] urls[4] = file:/Users/thoma/.m2/repository/org/sonatype/aether/aether-util/1.11/aether-util-1.11.jar
[ERROR] urls[5] = file:/Users/thoma/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
[ERROR] urls[6] = file:/Users/thoma/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[7] = file:/Users/thoma/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[8] = file:/Users/thoma/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[9] = file:/Users/thoma/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-tools-api/3.4/maven-plugin-tools-api-3.4.jar
[ERROR] urls[10] = file:/Users/thoma/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[11] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/jetty-util/9.3.7.v20160115/jetty-util-9.3.7.v20160115.jar
[ERROR] urls[12] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/jetty-webapp/9.3.7.v20160115/jetty-webapp-9.3.7.v20160115.jar
[ERROR] urls[13] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/jetty-xml/9.3.7.v20160115/jetty-xml-9.3.7.v20160115.jar
[ERROR] urls[14] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/jetty-servlet/9.3.7.v20160115/jetty-servlet-9.3.7.v20160115.jar
[ERROR] urls[15] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/jetty-quickstart/9.3.7.v20160115/jetty-quickstart-9.3.7.v20160115.jar
[ERROR] urls[16] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/jetty-jaas/9.3.7.v20160115/jetty-jaas-9.3.7.v20160115.jar
[ERROR] urls[17] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/jetty-security/9.3.7.v20160115/jetty-security-9.3.7.v20160115.jar
[ERROR] urls[18] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/jetty-plus/9.3.7.v20160115/jetty-plus-9.3.7.v20160115.jar
[ERROR] urls[19] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/jetty-jndi/9.3.7.v20160115/jetty-jndi-9.3.7.v20160115.jar
[ERROR] urls[20] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/jetty-server/9.3.7.v20160115/jetty-server-9.3.7.v20160115.jar
[ERROR] urls[21] = file:/Users/thoma/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar
[ERROR] urls[22] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/jetty-http/9.3.7.v20160115/jetty-http-9.3.7.v20160115.jar
[ERROR] urls[23] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/jetty-io/9.3.7.v20160115/jetty-io-9.3.7.v20160115.jar
[ERROR] urls[24] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/jetty-jmx/9.3.7.v20160115/jetty-jmx-9.3.7.v20160115.jar
[ERROR] urls[25] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/jetty-annotations/9.3.7.v20160115/jetty-annotations-9.3.7.v20160115.jar
[ERROR] urls[26] = file:/Users/thoma/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar
[ERROR] urls[27] = file:/Users/thoma/.m2/repository/org/ow2/asm/asm/5.0.1/asm-5.0.1.jar
[ERROR] urls[28] = file:/Users/thoma/.m2/repository/org/ow2/asm/asm-commons/5.0.1/asm-commons-5.0.1.jar
[ERROR] urls[29] = file:/Users/thoma/.m2/repository/org/ow2/asm/asm-tree/5.0.1/asm-tree-5.0.1.jar
[ERROR] urls[30] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/websocket/javax-websocket-server-impl/9.3.7.v20160115/javax-websocket-server-impl-9.3.7.v20160115.jar
[ERROR] urls[31] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/websocket/javax-websocket-client-impl/9.3.7.v20160115/javax-websocket-client-impl-9.3.7.v20160115.jar
[ERROR] urls[32] = file:/Users/thoma/.m2/repository/javax/websocket/javax.websocket-api/1.0/javax.websocket-api-1.0.jar
[ERROR] urls[33] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/websocket/websocket-server/9.3.7.v20160115/websocket-server-9.3.7.v20160115.jar
[ERROR] urls[34] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/websocket/websocket-common/9.3.7.v20160115/websocket-common-9.3.7.v20160115.jar
[ERROR] urls[35] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/websocket/websocket-api/9.3.7.v20160115/websocket-api-9.3.7.v20160115.jar
[ERROR] urls[36] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/websocket/websocket-client/9.3.7.v20160115/websocket-client-9.3.7.v20160115.jar
[ERROR] urls[37] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/websocket/websocket-servlet/9.3.7.v20160115/websocket-servlet-9.3.7.v20160115.jar
[ERROR] urls[38] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/apache-jsp/9.3.7.v20160115/apache-jsp-9.3.7.v20160115.jar
[ERROR] urls[39] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/toolchain/jetty-schemas/3.1/jetty-schemas-3.1.jar
[ERROR] urls[40] = file:/Users/thoma/.m2/repository/org/mortbay/jasper/apache-jsp/8.0.27/apache-jsp-8.0.27.jar
[ERROR] urls[41] = file:/Users/thoma/.m2/repository/org/mortbay/jasper/apache-el/8.0.27/apache-el-8.0.27.jar
[ERROR] urls[42] = file:/Users/thoma/.m2/repository/org/eclipse/jdt/core/compiler/ecj/4.4.2/ecj-4.4.2.jar
[ERROR] urls[43] = file:/Users/thoma/.m2/repository/org/eclipse/jetty/apache-jstl/9.3.7.v20160115/apache-jstl-9.3.7.v20160115.jar
[ERROR] urls[44] = file:/Users/thoma/.m2/repository/org/apache/taglibs/taglibs-standard-spec/1.2.5/taglibs-standard-spec-1.2.5.jar
[ERROR] urls[45] = file:/Users/thoma/.m2/repository/org/apache/taglibs/taglibs-standard-impl/1.2.5/taglibs-standard-impl-1.2.5.jar
[ERROR] urls[46] = file:/Users/thoma/.m2/repository/javax/transaction/javax.transaction-api/1.2/javax.transaction-api-1.2.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException`

Do you know what can be the issue here ? 

Thanks

**Comment by tbigueres** [comment]
Hi !
Yes indeed there is multiple versions of cgi. But I've seen that in the
package you included directly the classes instead of using the pom.xml ! So
this means we cannot exclude the cgi dependency when we import your package
!

Le mer. 29 août 2018 à 22:21, Diana De Rose <notifications@github.com> a
écrit :

**Comment by diana-derose** [comment]
Hi @tbigueres  - Could you please point me to where the classes are included directly?
It is in the pom file as far as I know but I could have overlooked if the class was added as well.
https://github.com/intuit/QuickBooks-V3-Java-SDK/blob/develop/pom.xml
