### ISSUE TITLE
Out of scope issue

### ISSUE THREAD

**Issue by mariobyn** [intuit/QuickBooks-V3-Java-SDK#43]
Hey all,

I'm having a problem while i am trying to create a customer for an invoice. The api throws me The access token does not have sufficient scope. When i am requesting the access token i specify the scope to be Accounting. 

Am i doing something wrong? Do i need to specify other scopes?

Thanks,
Marius.

**Comment by diana-derose** [comment]
Hi @mariobyn  - Can you check the base url in your app. This error can happen when you are using sandbox api url with prod tokens or vice-versa.
Here's the right url-
Sandbox: https://sandbox-quickbooks.api.intuit.com/v3/company
Production: https://quickbooks.api.intuit.com/v3/company

**Comment by mariobyn** [comment]
Hey Diana,

Thanks for the response, you are right, i forgot about the intuit-config.xml, that i need to modify there the link. My bad. You saved my day!

Thank you,
Marius.
