### ISSUE TITLE
Cookie rejected: Illegal 'domain' attribute "qbo.intuit.com". Domain of origin: "quickbooks.api.intuit.com"

### ISSUE THREAD

**Issue by dmitrygusev** [intuit/QuickBooks-V3-Java-SDK#44]
Getting lots of mentioned warnings in our logs:

Production:
> Cookie rejected [JSESSIONID="...", version:0, domain:qbo.intuit.com, path:/, expiry:null] Illegal 'domain' attribute "qbo.intuit.com". Domain of origin: "quickbooks.api.intuit.com"

Sandbox:
> Cookie rejected [JSESSIONID="...", version:0, domain:qbo.intuit.com, path:/, expiry:null] Illegal 'domain' attribute "qbo.intuit.com". Domain of origin: "sandbox-quickbooks.api.intuit.com"

Would be nice if we could clean these up somehow.

**Comment by diana-derose** [comment]
Hi @dmitrygusev - Which version of the SDK are you using? This was fixed in v4.03 https://github.com/intuit/QuickBooks-V3-Java-SDK/releases/tag/4.0.3
Let me know if you are still seeing the warnings.

**Comment by dmitrygusev** [comment]
We were still on 2.x, all fixed after updating to latest 4.0.8
