### ISSUE TITLE
ProxyConfig and NTCredentials

### ISSUE THREAD

**Issue by kedarpanse** [intuit/QuickBooks-V3-Java-SDK#48]
HttpRequestClient setProxyAuthentication only supports UsernamePassword credentials.  Most of the proxies in corporate use NTCredentials.  Perhaps we can allow it if username contains a / or \ ?  Apache HTTP client does support NTCredentials.  Here is snippet we can use? @diana-derose please check.
[NTCredentials.txt](https://github.com/intuit/QuickBooks-V3-Java-SDK/files/2977234/NTCredentials.txt)

**Comment by diana-derose** [comment]
Thanks for the suggestion, let me review your PR and get back to you.

**Comment by diana-derose** [comment]
Added in v5.0.3
