### ISSUE TITLE
Customer/Vendor ContactName

### ISSUE THREAD

**Issue by davidseywald** [intuit/QuickBooks-V3-Java-SDK#50]
Hello,
In the Vendor and Customer class there is a field contactName:

```
    @XmlElement(name = "ContactName")
    protected String contactName;
```
But this seems to be always empty and is not described in the API documentation.
Which fields should be used to get the (full) name of this customer/vendor? DisplayName?
We are using QuickBooks java SDK 5.0.4. 
Thank you

**Comment by diana-derose** [comment]
Hi @davidseywald  - DisplayName or FullyQualifiedName is usually better. With FullyQualifiedName, you might see additional data appended the contact is a sub customer.
