### ISSUE TITLE
Use AccountSubTypeEnum instead of String in Account

### ISSUE THREAD

**Issue by davidseywald** [intuit/QuickBooks-V3-Java-SDK#52]
In `com.intuit.ipp.data.Account` there is a field:
```
    @XmlElement(name = "AccountSubType")
    protected String accountSubType;
```
There is also an Enum `com.intuit.ipp.data.AccountSubTypeEnum`.
Is it possible to use the Enum instead of a String (same as for `accountType` and `classification`) - assuming this is the same thing?

We are currently using `AccountSubTypeEnum.fromValue()` to convert the String to Enum,
but getting an `IllegalArgumentException` for "_IncomeTaxPayable_"

Thank you.

**Comment by diana-derose** [comment]
Hi @davidseywald  - Ideally enum would be the right option. However, we used string for account subtypes because there have been instances where the API has introduced new sub types without a minor version and this can cause serialization errors for clients using an older version of the SDK.
