### ISSUE TITLE
Documentation Update: Multi-threaded application

### ISSUE THREAD

**Issue by cjgratacos** [intuit/QuickBooks-V3-Java-SDK#53]
Highly suggest a documentation update to help and point out that whenever working on a multi-threaded application and the [Config](https://github.com/intuit/QuickBooks-V3-Java-SDK/blob/59f988d0776d46620d0b34711c411b2b5b1da06b/ipp-v3-java-devkit/src/main/java/com/intuit/ipp/util/Config.java) gets updated programmatically (instead of using the `config.xml`), the config needs to be updated on each thread which makes a request due to this: https://github.com/intuit/QuickBooks-V3-Java-SDK/blob/59f988d0776d46620d0b34711c411b2b5b1da06b/ipp-v3-java-devkit/src/main/java/com/intuit/ipp/util/Config.java#L191. If this is not done per thread, then the applied programmatically configuration will not be applied.

**Comment by diana-derose** [comment]
@cjgratacos  - Thanks for the feedback, I have created a story on our end to update the documentation. We'll probably take it up next sprint.

**Comment by diana-derose** [comment]
Updated documentation- https://developer.intuit.com/app/developer/qbo/docs/develop/sdks-and-samples-collections/java/configuration
