### ISSUE TITLE
payments API doesn't support card track data

### ISSUE THREAD

**Issue by pfullbright-mf** [intuit/QuickBooks-V3-Java-SDK#56]
Currently, the API doesn't support card track data. Is this planned? Can I contribute it? If not, can you give me a reason? We are migrating from old qbms, and this is a bit of a blocker, as we use track data in our existing qbms implementation.

**Comment by diana-derose** [comment]
Hi @pfullbright-mf - Could you provide more details on what you mean by card track data?
The SDK has support for all operations mentioned in the APIReference below, let me know what's missing and I can add it. You are welcome to contribute as well.
https://developer.intuit.com/app/developer/qbpayments/docs/api/resources/all-entities/bankaccounts

**Comment by pfullbright-mf** [comment]
Yes, try this charge call:
{
	"amount": 25.00,
	"currency": "USD",
	"card": {
		"name": "Dave Patient",
		"address": {
			"postalCode": "27519"
		},
		"cardPresent": {
			"track2": ";4055011111111111=19121015432112345678?"
		}
	},
	"context": {
		"mobile": "false",
		"isEcommerce": "false"
	},
	"capture": false
}

This is API that I understand to be fully supported, though not documented (I am not sure why.) Our QBMS application uses this sort of card authorization all the time. We can make API calls using just the REST API, but it would be super helpful if we could get the java SDK to support this as well.

(This was a sandbox call, btw, with test card data.)

**Comment by diana-derose** [comment]
Thanks, I have confirmed with the team that these can be added to the API. I'll add it in the next release (next week). We'll also update the documentation.

**Comment by pfullbright-mf** [comment]
Awesome! Thanks!

**Comment by diana-derose** [comment]
Added this in v6.0.1
