### ISSUE TITLE
Improve code coverage

### ISSUE THREAD

**Issue by diana-derose** [intuit/QuickBooks-V3-Java-SDK#60]
Goal :
To improve the test coverage.

Coverage needed in the following projects:
[oauth2-platform-api](https://github.com/intuit/QuickBooks-V3-Java-SDK/tree/develop/oauth2-platform-api/src/test)
[payments-api](https://github.com/intuit/QuickBooks-V3-Java-SDK/tree/develop/payments-api/src/test)
[IPP-Java-Devkit](https://github.com/intuit/QuickBooks-V3-Java-SDK/tree/develop/ipp-v3-java-devkit/src/test)

Guidelines:
If adding a new file, please include copyright notice, [sample here](https://github.com/intuit/QuickBooks-V3-Java-SDK/blob/develop/oauth2-platform-api/src/test/java/com/intuit/oauth2/client/DiscoveryAPIClientTest.java#L1-L15)

**Comment by praveenadg** [comment]
I am going to take a dip at payments-api

**Comment by yjain3326** [comment]
I can take a look at oauth2-platform-api if this is still available.

**Comment by diana-derose** [comment]
@yjain3326  - Sure go ahead

**Comment by k-arjun** [comment]
I'll take a dip at some of the payments-api classes too.

**Comment by cho8** [comment]
Taking a look at the IPP-Java-Devkit tests

**Comment by tarungulati1988** [comment]
I'll add a few too. Will start with the interceptors.

**Comment by diana-derose** [comment]
Awesome!!! thank you all of you!

**Comment by amatiushkin** [comment]
adding test for callback interceptor

**Comment by shivamagarwal7** [comment]
@diana-derose, I will add some tests too.

**Comment by symborsk** [comment]
@diana-derose Have added two PRs to increase coverage in:
[Payment-API](https://github.com/intuit/QuickBooks-V3-Java-SDK/pull/68)
[v3-Java-Devkit](https://github.com/intuit/QuickBooks-V3-Java-SDK/pull/69)

**Comment by shettyvinay** [comment]
@diana-derose I would like to work on IPP-Java-Devkit coverage

**Comment by jackykc** [comment]
Taking a look at payments-api, starting with model then adding some in services

**Comment by megha276** [comment]
@diana-derose Have added 1 PR to increase code coverage for Payment-API

**Comment by pduvvur** [comment]
I can add tests for `ECheckService` in payments-api. @jackykc

**Comment by jackykc** [comment]
> I can add tests for `ECheckService` in payments-api. @jackykc

I'll take a look at the `TokenService` then move on to another service after

**Comment by harry0123** [comment]
Hi y'all! I'm relatively new to this project so I'll increase coverage in some data classes (`com.intuit.payment.data`). Here's what my coverage report in IntelliJ is showing as of https://github.com/intuit/QuickBooks-V3-Java-SDK/commit/eaeb2e6ce90cb442dc966af92d9ad97132fa438f:
<img width="614" alt="Screen Shot 2019-10-29 at 3 28 50 PM" src="https://user-images.githubusercontent.com/2097770/67814402-39ccb700-fa61-11e9-8c37-f0cdc6a71e5a.png">

so I'll start with the 0% Line coverage in alphabetical order.

**Comment by symborsk** [comment]
No

**Comment by symborsk** [comment]
Apologies the previous was an accidental apply via a smart watch.

-Johm

**Comment by harry0123** [comment]
No worries, mate! If there are other classes that I should focus on, let me know!

**Comment by diana-derose** [comment]
Thank you all for the PR's, please keep them coming! @harry0123  - I just merged a few PRs some of which had tests for data classes. Please pull the latest code and start writing the tests to avoid duplication.

**Comment by tfung** [comment]
@diana-derose I added the above PR! Please take a look.

**Comment by vrohit13** [comment]
@diana-derose Added tests for ChargeService https://github.com/intuit/QuickBooks-V3-Java-SDK/pull/104

**Comment by codefupanda** [comment]
@diana-derose Please check https://github.com/intuit/QuickBooks-V3-Java-SDK/pull/107 adds tests for BankAccountService

**Comment by diana-derose** [comment]
Hello everyone, all PR's are merged. With your help the code coverage rose from 33% to ~70%, especially payments-api rose from 11% to 92%. Great job everyone and thanks for contributing!!!!
